### ISSUE TITLE
Error unlinking spreadsheet

### ISSUE THREAD

**Issue by wilddom** [nextcloud/forms#2528]
**Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!**

**Describe the bug**
Unlinking a spreadsheet causes a JavaScript TypeError (see screenshot or log)

**Screenshots**
![Image](https://github.com/user-attachments/assets/ad2e1830-e44b-470d-80c8-bb95629ab41b)

**Nextcloud (please complete the following information):**

- Nextcloud-Version: 30.0.5
- Forms-Version: 4.3.5

**Browser log**
```
vendor-C9uUsabI.chunk.mjs:2 TypeError: K.update is not a function
    at s.onUnlinkFile (forms-main.mjs?v=93611462-4:5:40604)
    at me (vendor-C9uUsabI.chunk.mjs:2:23739)
    at s.n (vendor-C9uUsabI.chunk.mjs:2:13959)
    at me (vendor-C9uUsabI.chunk.mjs:2:23739)
    at e.$emit (vendor-C9uUsabI.chunk.mjs:2:29326)
    at s.onClick (NcSettingsSection-DHX2Y1Ed-CbC7YZik.chunk.mjs:950:8439)
    at s.handleClick (NcSettingsSection-DHX2Y1Ed-CbC7YZik.chunk.mjs:950:9791)
    at me (vendor-C9uUsabI.chunk.mjs:2:23739)
    at HTMLButtonElement.n (vendor-C9uUsabI.chunk.mjs:2:13959)
    at Qc.i._wrapper (vendor-C9uUsabI.chunk.mjs:2:60813)
```

**Comment by Chartman123** [comment]
I can confirm it, same error message for me. @Koc could you please have a look at it?

**Comment by Koc** [comment]
seems like it was broken since #2222.

![Image](https://github.com/user-attachments/assets/4735988d-6511-4b0d-96d8-029815786c92)

Here the fix #2534, but I can't compile and test it due to an error:

```
devcontainer@e0e910ca5f18:/var/www/html/apps/forms$ npm run dev

> forms@5.0.0-alpha.1 dev
> vite --mode development build

Building forms for development
error during build:
TypeError: crypto$2.getRandomValues is not a function
    at resolveConfig (file:///var/www/html/apps/forms/node_modules/vite/dist/node/chunks/dep-CHZK6zbr.js:66562:16)
    at async build (file:///var/www/html/apps/forms/node_modules/vite/dist/node/chunks/dep-CHZK6zbr.js:65395:18)
    at async CAC.<anonymous> (file:///var/www/html/apps/forms/node_modules/vite/dist/node/cli.js:829:5)
```
